# Generated by Django 5.0.6 on 2024-05-21 15:15

import HospitalGestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitasMedicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('identificacion', models.CharField(max_length=20)),
                ('especialidad', models.CharField(choices=[(HospitalGestion.models.Especialidad['Pediatria'], 'Pediatria'), (HospitalGestion.models.Especialidad['Cardiologia'], 'Cardiologia'), (HospitalGestion.models.Especialidad['Dermatologia'], 'Dermatologia')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('identificacion', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpedienteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=50)),
                ('tratamiento', models.CharField(max_length=50)),
                ('prescripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GestionCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
